### ISSUE TITLE
How to run on mac

### ISSUE THREAD

**Issue by sujitshodangi** [kodamap/face_reidentification_demo#1]
Hi 

Could you please advise how to run on mac.

python3 app.py -i cam

Currently getting below error. Not sure about --cpu_extension
Please try to specify cpu extensions library path in demo's command line parameters using -l or --cpu_extension command line argument

**Comment by kodamap** [comment]
@sujitshodangi 

Unfortunately I can not tried this on Mac though, if you use  OpenVINO toolkit 2019 R3 build or earlier I think this issue helps you.　

Please try to specify `libcpu_extension_avx2.so` with `-l` option.
https://github.com/kodamap/tellooo/issues/4

If you use 2020.1 build `libcpu_extension_avx2.so` would not be found because it removed in the verison. You could try the 2019 R3 build.
https://software.intel.com/en-us/forums/intel-distribution-of-openvino-toolkit/topic/848825
